name: Emscripten build and test
on: [push]
env:
    CMAKE_VERSION: 3.10.0
    NINJA_VERSION: 1.10.0
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Setup Emscripten toolchain
              uses: mymindstorm/setup-emsdk@v11

            - name: Install ninja
              uses: seanmiddleditch/gha-setup-ninja@v3

            - name: Install cmake
              uses: jwlawson/actions-setup-cmake@v1.12

            - name: Setup Node.js environment
              uses: actions/setup-node@v3.3.0

            - name: Build and test Emscripten Debug
              run: |
                  mkdir Debug
                  cd Debug
                  cmake .. --preset emscripten-debug
                  cmake --build .
                  ctest --output-on-failure

            - name: Build and test Emscripten Release
              run: |
                  mkdir Release
                  cd Release
                  cmake .. --preset emscripten-release
                  cmake --build .
                  ctest --output-on-failure