name: Build and test Windows x64
on: [push]
env:
    CMAKE_VERSION: 3.10.0
    NINJA_VERSION: 1.10.0
jobs:
    build:
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v2

            - name: Install ninja
              uses: seanmiddleditch/gha-setup-ninja@v3

            - name: Install cmake
              uses: jwlawson/actions-setup-cmake@v1.12

            - name: Build Debug
              run: |
                  mkdir Debug
                  cd Debug
                  cmake .. --preset x64-debug
                  cmake --build .
                  ctest --output-on-failure

            - name: Test Debug
              run: ctest --output-on-failure

            - name: Build Release
              run: |
                  mkdir Release
                  cd Release
                  cmake .. --preset x64-release
                  cmake --build .
                  ctest --output-on-failure

            - name: Test Release
              run: ctest --output-on-failure